# Generated by Django 3.1.7 on 2021-03-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbsnote', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
